name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Set up Codacy script
        run: curl -o get.sh -Ls https://coverage.codacy.com/get.sh

      - name: Set up Just
        uses: taiki-e/install-action@just@v2

      - name: Run tests with coverage
        run: just test

      - name: Export commit SHA
        run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Upload to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: bash get.sh report --force-coverage-parser go -r coverage.pprof --commit-uuid "$COMMIT_SHA"
